# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Warp IDE Container Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Extract version from Cargo.toml
      id: cargo_version
      run: |
        VERSION=$(grep '^version =' Cargo.toml | sed -E 's/version = "(.*)"/\1/')
        echo "Version is $VERSION"
        echo "cargo_version=$VERSION" >> "$GITHUB_OUTPUT"


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ide
        push: true
        tags: |
          ghcr.io/cw-warp/ide:latest
          ghcr.io/cw-warp/ide:${{ steps.cargo_version.outputs.cargo_version }}